Repository TheSylwio/employee-management-system, pull requests merged in 2020-12, with the labels that each got.

#55 reCaptcha
  composer.json
  src/Controller/SecurityController.php
  src/Security/MainAuthenticator.php
  templates/base.html.twig
  templates/security/login.html.twig
Labels: backend, frontend, low priority

#59 Created entity constraints
  src/Entity/Employee.php
  src/Entity/Event.php
  src/Entity/Milestone.php
  src/Entity/Post.php
  src/Entity/Status.php
  src/Entity/Task.php
Labels: backend

#54 Sidebar
  assets/app.js
  assets/js/sidebar.js
  assets/styles/app.scss
  assets/styles/sidebar.scss
  config/packages/google_recaptcha.yaml
  config/services.yaml
  package-lock.json
  package.json
  src/DataFixtures/AppFixtures.php
  templates/base.html.twig
  templates/layouts/navbar.html.twig
  templates/layouts/sidebar.html.twig
Labels: frontend

#69 Improvements
  assets/app.js
  assets/js/sidebar.js
  assets/styles/app.scss
  assets/styles/sidebar.scss
  templates/base.html.twig
  templates/documents/index.html.twig
  templates/employees/add.html.twig
  templates/employees/edit.html.twig
  templates/employees/index.html.twig
  templates/events/add.html.twig
  templates/events/edit.html.twig
  templates/events/index.html.twig
  templates/index/add_post.html.twig
  templates/index/index.html.twig
  templates/layouts/sidebar.html.twig
  templates/milestones/add.html.twig
  templates/milestones/description.html.twig
  templates/milestones/edit.html.twig
  templates/milestones/index.html.twig
  templates/security/login.html.twig
  templates/settings/change_email.html.twig
  templates/settings/change_password.html.twig
  templates/settings/index.html.twig
  templates/status/add.html.twig
  templates/status/index.html.twig
  templates/tasks/add.html.twig
  templates/tasks/edit.html.twig
  templates/tasks/index.html.twig
Labels: frontend, low priority
