Repository TheSylwio/employee-management-system, pull requests merged in 2021-01, with the labels that each got.

#71 Toast
  assets/app.js
  assets/js/toast.js
  assets/styles/app.scss
  package.json
  src/Controller/DocumentsController.php
  src/Controller/EmployeeController.php
  src/Controller/EventsController.php
  src/Controller/IndexController.php
  src/Controller/MilestonesController.php
  src/Controller/StatusController.php
  src/Controller/TaskController.php
  templates/base.html.twig
  templates/employees/index.html.twig
  templates/events/index.html.twig
  templates/milestones/description.html.twig
  templates/milestones/index.html.twig
  templates/settings/index.html.twig
  templates/status/index.html.twig
  templates/tasks/index.html.twig
Labels: frontend, low priority

#72 Fixes
  src/Controller/EmployeeController.php
  src/Controller/EventsController.php
  src/Controller/IndexController.php
  src/Controller/MilestonesController.php
  src/Controller/StatusController.php
  src/Controller/TaskController.php
  src/Entity/Company.php
  src/Entity/Status.php
  templates/employees/index.html.twig
  templates/index/index.html.twig
Labels: high priority

#73 Team management
  src/Controller/TaskController.php
  src/Controller/TeamController.php
  src/DataFixtures/TeamFixtures.php
  src/Entity/Company.php
  src/Entity/Employee.php
  src/Entity/Team.php
  src/Form/TaskType.php
  src/Form/TeamType.php
  templates/employees/index.html.twig
  templates/layouts/sidebar.html.twig
  templates/tasks/add.html.twig
  templates/tasks/edit.html.twig
  templates/team/add.html.twig
  templates/team/edit.html.twig
  templates/team/index.html.twig
Labels: backend, in progress

#74 Vacation
  assets/js/flatpickr.js
  package-lock.json
  src/Controller/VacationController.php
  src/Entity/Company.php
  src/Entity/Employee.php
  src/Entity/Vacation.php
  src/Form/VacationStatusType.php
  src/Form/VacationType.php
  src/Repository/VacationRepository.php
  templates/layouts/sidebar.html.twig
  templates/vacation/add.html.twig
  templates/vacation/edit.html.twig
  templates/vacation/index.html.twig
Labels: backend, database, frontend

#76 Dev/subpages
  assets/styles/app.scss
  assets/styles/subpage.scss
  templates/documents/index.html.twig
  templates/employees/add.html.twig
  templates/employees/edit.html.twig
  templates/employees/index.html.twig
  templates/events/add.html.twig
  templates/events/edit.html.twig
  templates/events/index.html.twig
  templates/index/add_post.html.twig
  templates/index/index.html.twig
  templates/milestones/add.html.twig
  templates/milestones/description.html.twig
  templates/milestones/edit.html.twig
  templates/milestones/index.html.twig
  templates/settings/change_email.html.twig
  templates/settings/change_password.html.twig
  templates/settings/index.html.twig
  templates/status/add.html.twig
  templates/status/index.html.twig
  templates/tasks/add.html.twig
  templates/tasks/edit.html.twig
  templates/tasks/index.html.twig
  templates/team/add.html.twig
  templates/team/edit.html.twig
  templates/team/index.html.twig
  templates/vacation/add.html.twig
  templates/vacation/edit.html.twig
  templates/vacation/index.html.twig
Labels: frontend, high priority

#75 Dev/overtime
  assets/js/flatpickr.js
  src/Controller/OvertimeController.php
  src/Entity/Company.php
  src/Entity/Overtime.php
  src/Form/OvertimeStatusType.php
  src/Form/OvertimeType.php
  src/Form/VacationType.php
  src/Repository/OvertimeRepository.php
  templates/layouts/sidebar.html.twig
  templates/overtime/add.html.twig
  templates/overtime/disposition.html.twig
  templates/overtime/edit.html.twig
  templates/overtime/index.html.twig
Labels: backend, database, frontend, medium priority
